name: clock
description: A new Flutter project.
publish_to: 'none'
version: 1.1.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  logger: ^1.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  numberpicker: ^2.1.2
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
